# Workflow
# Should Have Name
name: Hello

on:
  workflow_dispatch:

# jobs is an object needs Indentation
jobs:                                     
  say-hello:
    # create Ephermal Container With Ubuntu Running                             
    runs-on: ubuntu-latest
     # steps inside the jobs
    steps:                               
      - name: Say hello to everyone
        run: echo "Hello Brother"


